# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = [workspace 1 silent] omarchy-launch-webapp
exec-once = [workspace 2 silent] terminal
exec-once = [workspace 3 silent] obisidian
exec-once = [workspace 5 silent] omarchy-launch-webapp "https://music.youtube.com/"
