# Extra autostart processes
# exec-once = uwsm-app -- my-service

# cliphist config
exec-once = uwsm app -- wl-paste --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

# workspace configs
exec-once = [workspace 1 silent] chromium --profile-directory="Profile 1"
exec-once = [workspace 2 silent] ghostty
exec-once = [workspace 3 silent] dbeaver

# launch the app on workspace 5 every time it's empty
workspace = 5, on-created-empty:omarchy-launch-webapp "https://music.youtube.com/"

