# Extra autostart processes
# exec-once = uwsm-app -- my-service

# cliphist config
exec-once = uwsm app -- wl-paste --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

# workspace configs
exec-once = [workspace 1 silent] omarchy-launch-webapp
exec-once = [workspace 2 silent] ghostty
exec-once = [workspace 3 silent] sleep 3; obisidian
exec-once = [workspace 5 silent] sleep 4; omarchy-launch-webapp "https://music.youtube.com/"
